spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ancient_poetry?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

mybatis:
  # ��Ҫ����
  type-aliases-package: com.moon.ancientpoetry.common.po
